## Create and Train an LR Model
### We'll start by creating a linear regression model with data from insurance ( highly used public dataset) modified.

In [11]:
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
# Generate some dummy data
X = np.random.rand(100, 1) *10   # 100 samples, 1 feature
y = 2 * X + 1 + np.random.randn(100, 1) * 2  # y = 2x + 1 + noise

In [13]:
print(X)

[[4.68751901]
 [0.983429  ]
 [4.50423076]
 [4.58950139]
 [2.15990571]
 [7.82663248]
 [9.2965516 ]
 [0.68971647]
 [9.14371111]
 [8.66108853]
 [6.78838495]
 [6.66332925]
 [2.83448836]
 [0.30635102]
 [6.59591216]
 [0.83203251]
 [2.18710837]
 [3.54167351]
 [0.67011851]
 [2.72524271]
 [6.74176876]
 [1.96610301]
 [4.2195407 ]
 [5.29299631]
 [6.95622521]
 [2.61885335]
 [6.05239548]
 [3.36028042]
 [5.1244755 ]
 [7.59513547]
 [6.72756041]
 [1.67478433]
 [4.81449837]
 [2.71741921]
 [4.99035477]
 [2.14943387]
 [0.18178063]
 [1.34039981]
 [7.66779412]
 [2.39235475]
 [5.092523  ]
 [2.30540597]
 [4.1702869 ]
 [1.12818578]
 [2.67737698]
 [7.88494835]
 [6.35920756]
 [3.41998035]
 [2.43333822]
 [7.33070357]
 [0.6062235 ]
 [0.30321664]
 [0.962371  ]
 [3.70436952]
 [4.51288972]
 [7.61104368]
 [4.86293335]
 [7.98321735]
 [0.44894808]
 [6.52858779]
 [6.08207014]
 [9.11684035]
 [5.65173283]
 [3.26341602]
 [3.04299787]
 [8.48438857]
 [2.66365976]
 [5.38742224]
 [5.31305048]
 [2.8761827 ]
 [3.52369754]
 [7.24

In [14]:
print(y)

[[11.32326631]
 [ 3.3490869 ]
 [ 9.82162267]
 [ 8.99607782]
 [ 1.24755636]
 [16.20615799]
 [20.43130612]
 [ 3.16598984]
 [19.05152833]
 [22.04454112]
 [12.44890029]
 [15.0947196 ]
 [ 7.10421855]
 [ 0.43654331]
 [13.82571093]
 [ 1.72956131]
 [ 8.16855261]
 [ 8.51991834]
 [ 1.65854769]
 [ 7.65818309]
 [12.33222685]
 [ 7.24441151]
 [12.53515978]
 [10.79420889]
 [15.95093783]
 [ 3.38973295]
 [14.98485393]
 [ 6.39406429]
 [10.77214186]
 [18.71169869]
 [19.76881866]
 [ 4.43127346]
 [13.36714183]
 [ 6.5017572 ]
 [11.80512325]
 [ 6.79541675]
 [ 1.92812588]
 [ 2.76613154]
 [19.29020672]
 [ 8.31444645]
 [12.7506568 ]
 [ 6.0231814 ]
 [ 9.44953381]
 [ 3.2679112 ]
 [ 3.1694679 ]
 [18.42883384]
 [15.1722977 ]
 [10.08303654]
 [ 5.33888301]
 [16.71819008]
 [ 2.06805812]
 [-1.59050767]
 [ 1.45013926]
 [ 7.73841683]
 [11.29842993]
 [20.03067712]
 [11.17305304]
 [19.67376567]
 [ 3.26166399]
 [16.29289847]
 [14.1269836 ]
 [16.28141748]
 [11.87286486]
 [ 2.77665067]
 [ 8.76002828]
 [16.57647398]
 [ 7.25120

In [15]:
data  = pd.read_csv('insurance-short.csv')
data.head(4)

age     sex   bmi  children smoker     region  expenses
0   18    male  16.0         0     no  northeast   1694.80
1   18    male  17.3         2    yes  northeast  12829.46
2   18  female  20.8         0     no  southeast   1607.51
3   18    male  21.5         0     no  northeast   1702.46

In [19]:
#X, y = data.data, data.target

# Drop rows with missing values
df_cleaned = data.dropna(subset=['bmi'])


#X = df_cleaned[  ['bmi']   ]
#y = df_cleaned[['expenses']]


# Prepare your data
X = df_cleaned[df["bmi"],]
y = df_cleaned[df['expenses'],]


KeyError: ('bmi',)

In [18]:
print(X)

       bmi
0     16.0
1     17.3
2     20.8
3     21.5
4     21.6
...    ...
1333  39.1
1334  39.2
1335  39.3
1336  39.7
1337  40.5

[1338 rows x 1 columns]


In [10]:
# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create a linear regression model
model = LinearRegression()

# Train the model
model.fit(X_train, y_train)

LinearRegression()

In [11]:
from skl2onnx import convert_sklearn
from skl2onnx.common.data_types import FloatTensorType

# Define the initial types for the ONNX model
#initial_type = [('float_input', FloatTensorType([None, X_train.shape[1]  ]))]

initial_type = [('float_input', FloatTensorType([None, X_train.shape[1]  ]))]

# Convert the scikit-learn model to ONNX
onnx_model = convert_sklearn(model, initial_types=initial_type)

# Save the ONNX model to a file
with open("linear_regression-ins.onnx", "wb") as f:
    f.write(onnx_model.SerializeToString())

## Save the model
### Save the model in Json format

## Transpile your model to Orion Cairo
### We will use Giza-CLI to transpile our saved model to Orion Cairo.


$ giza transpile 

## Deploy an inference endpoint
### Now that our model is transpiled to Cairo we can deploy an endpoint to run verifiable inferences. We will use Giza CLI again to run and deploy an endpoint. Ensure to replace model-id and version-id with your ids provided during transpilation.


giza endpoints deploy --model-id 665 --version-id 1

$ giza endpoints deploy --model-id XXX --version-id X


## Run a verifiable inference
##### To streamline verifiable inference, you might consider using the endpoint URL obtained after transpilation. However, this approach requires manual serialization of the input for the Cairo program and handling the deserialization process. To make this process more user-friendly and keep you within a Python environment, we've introduced a Python SDK designed to facilitate the creation of ML workflows and execution of verifiable predictions. When you initiate a prediction, our system automatically retrieves the endpoint URL you deployed earlier, converts your input into Cairo-compatible format, executes the prediction, and then converts the output back into a numpy object. 

In [13]:
from giza.agents.model import GizaModel

MODEL_ID = 719  # Update with your model ID
VERSION_ID = 3  # Update with your version ID

def prediction(input, model_id, version_id):
    model = GizaModel(id=model_id, version=version_id)

    (result, proof_id) = model.predict(
        input_feed={'input': input}, verifiable=True
    )

    return result, proof_id

def execution():
    # The input data type should match the model's expected input

    input = np.array([[30.1]]).astype(np.float32)
    #input = np.array([[31,28.1]]).astype(np.float32)
    (result, proof_id) = prediction(input, MODEL_ID, VERSION_ID)

    print(
        f"Predicted value for input {input.flatten()[0]} is {result[0].flatten()[0]}")

    return result, proof_id


execution()

🚀 Starting deserialization process...
✅ Deserialization completed! 🎉
Predicted value for input 30.100000381469727 is 13053.928756713867


(array([[13053.92875671]]), 'b7ee4fb8426644c3a6f12a7a72a95b8d')

## Download the proof
#### Initiating a verifiable inference sets off a proving job on our server, sparing you the complexities of installing and configuring the prover yourself. Upon completion, you can download your proof.

First, let's check the status of the proving job to ensure that it has been completed.

$ giza endpoints get-proof --endpoint-id XXX --proof-id "xxxxxxxxxxxxxxxxxxxxxxxxxx"
[giza][2024-05-30 00:40:39.691] Getting proof from endpoint xxx
{
  "id": 967,
  "job_id": 1121,
  "metrics": {
    "proving_time": 17.249508
  },
  "created_date": "2024-05-30T07:33:12.532659"
}

Once the proof is ready, you can download it.

$ giza endpoints download-proof --endpoint-id xxx --proof-id "xxxxxxxxxxxxxxxxx" --output-path zk_xgboost.proof
[giza][2024-05-30 00:51:52.048] Getting proof from endpoint xxx ✅
[giza][2024-05-30 00:51:53.800] Proof downloaded to zk_xgboost.proof ✅
(giza3)

## Verify the proof
#### Finally, you can verify the proof.

$ giza verify --proof-id 967
[giza][2024-05-30 00:56:05.847] Verifying proof...
[giza][2024-05-30 00:56:07.140] Verification result: True
[giza][2024-05-30 00:56:07.145] Verification time: 0.454667226
(giza3)